"""Frozen remote-action protocol enumerations."""

from enum import StrEnum


class MessageType(StrEnum):
    WORK_ORDER_DELIVER = "WORK_ORDER_DELIVER"
    COMMAND_ACK = "COMMAND_ACK"
    WORK_ORDER_CANCEL = "WORK_ORDER_CANCEL"
    PROGRESS_EVENT = "PROGRESS_EVENT"
    TERMINAL_REFERENCE = "TERMINAL_REFERENCE"
    RECONCILE_REQUEST = "RECONCILE_REQUEST"
    RECONCILE_RESPONSE = "RECONCILE_RESPONSE"


class AckKind(StrEnum):
    RECEIVED = "RECEIVED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    ALREADY_TERMINAL = "ALREADY_TERMINAL"


class ProgressStatus(StrEnum):
    RUNNING = "RUNNING"
    VERIFYING = "VERIFYING"
    RECONCILING = "RECONCILING"
    CHECKPOINT_BLOCKED = "CHECKPOINT_BLOCKED"


class OutcomeStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    PARTIALLY_SUCCEEDED = "PARTIALLY_SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    UNVERIFIED = "UNVERIFIED"


class SideEffectState(StrEnum):
    NONE = "NONE"
    CONFIRMED = "CONFIRMED"
    UNCERTAIN = "UNCERTAIN"
    MIXED = "MIXED"


class EffectStatus(StrEnum):
    SKIPPED = "SKIPPED"
    FAILED_PRE_EFFECT = "FAILED_PRE_EFFECT"
    CONFIRMED = "CONFIRMED"
    UNCERTAIN = "UNCERTAIN"


class PermitStatus(StrEnum):
    ISSUED = "ISSUED"
    CLOSED_UNUSED = "CLOSED_UNUSED"
    CONFIRMED = "CONFIRMED"
    UNCERTAIN = "UNCERTAIN"


class ErrorCategory(StrEnum):
    VALIDATION = "VALIDATION"
    RESOURCE = "RESOURCE"
    TRANSIENT = "TRANSIENT"
    BUSINESS = "BUSINESS"
    CANCELLED = "CANCELLED"
    SIDE_EFFECT_UNCERTAIN = "SIDE_EFFECT_UNCERTAIN"
